language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudev-dev

before_script: ls
 
script:
  - make 

before_deploy:
  - find . 
  - export FILE_TO_UPLOAD=$(ls _builds/*/k81x_fkeys-*.tar.gz)

deploy:
  provider: releases
  file_glob: true
  file:
  - "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true
    repo: themech/k810_k811_fkeys
  api_key:
    secure: "RS8wLU62KoAYCbIdrb9tDsLrqWRk5dVS3I0+beukdkOzLoEtduEcNRw4OjJVwR2GW8aM4OxCIi6k7UuOFYtjJw6r4j/PYQvbg3GjghjoHxMbrmzTAjZCtBttPXHGla72xMKqg46xXK3YKvIHzgBxJx2SQ2Gvnmh7SGWyUsxvcVqCDOKI6cczSrlIQBsyChA18BI7iEKmeTlKXiKGHBSzEmIYWitzEqwKfHbbaxrMvGUvbw+AxJpkYLvAl1c8iee/8MKJ9AsY3YKbTcEp4EnQgzEaeuZqTVCA1mZuiXUxEiL1UILvi40E4JA7EXeSJSXxJQXN1rxA6Kw8PtoWhz8aRJ7ouhIHRZOedg8ab/4MobsY0anfp5fNo9/v5grOtfznbG/StoqLtprUOTG/vtMUIgYlGc3us6GH1F26YUPeSd0ebhSmvHeiLEbl9ryt+TCUEq4IeO+VmiOPaLhCraPrSv++kxw47EcuEPNj3qYWSxtHxV+hNAVfnzuIjN6zWGLxjZk2I9ZBuzt2GPEeyJguOlgGJNfrvGOEIqhplrWc01eEtSBjo09TnW4V3bEghmNDKzKU9pvcwLiN+OMbjVdIxfBPT+dz2ZzZz4bMlX78BehvP/j9/+TAjMBzqNXMgaYt64MN+/odTjcFIHuul8uCQE0D4KRNagT+iejo9AclFKE="
