sudo: false
language: cpp

addons:
  apt:
    packages:
    - libudev-dev

before_script: ls
 
script:
  - make 

before_deploy:
  - dpkg-buildpackage -us -uc -b
  - export FILE_TO_UPLOAD=$(ls ../k81x-fkeys*.deb)

os:
- linux
deploy:
  provider: releases
  file_glob: true
  file:
  - "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true
    repo: themech/k810_k811_fkeys
  api_key:
    secure: "$GITHUB_SECURE_TOKEN"
