language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudev-dev

before_script: ls
 
script:
  - make 

before_deploy:
  - find . 

deploy:
  provider: releases
  file_glob: true
  file:
  - "$HOME/gopath/bin/konfigurator-xc/*/konfigurator_*.tar.gz"
  - "$HOME/gopath/bin/konfigurator-xc/*/konfigurator_*.zip"
  - "$HOME/gopath/bin/konfigurator-xc/*/konfigurator_*.deb"
  skip_cleanup: true
  on:
    tags: true
    repo: themech/k810_k811_fkeys
  api_key:
    secure: 07www59Pp+fiXNlsCdKbBtan+XrU2OBMu4qCoJ+pZN16fKRHvKmiIRKyAUh0mEy2qgOMfU1v1sapN3ycatRKTacnLYWxIFM1eRO1GEuBHDRFiMC0D1MJldygry1oBEKDUUPoJJeCkWUjeBdkmJHE6sz9JZj8AZHea/QZcRD4d/yhzraiA9IKRr/IbjtyDS+bb8ERETdc6+TEFjdK2z/3K7Bm26aE1fSXbq6apePdk+dnHTd0EUacyszG5vIV/CIfrWWuGwv3jaLcy+8/51x+SOJD6aDi7/6nPNGadTq21vdduMOWIIf/jTVlEivyVQ6DarPJl1z2lHtCgZ1wuWkl4J//IMoOM4e4TqQosZcpFDTPaQd0mvh2Bu6MTkjs+KB/aJnzBUciCwtm96wqs+XWpDCBZwJLif1YSvigfPY6LkaJqk6/+qakMZU2Lvz/hdDZYqQtZK9dC35DlHE5uLY6lAlPdDMhE60AIPCi7PK1w9NSRaCIOjKPBagRlsDD0htmVu/DLH9Cnt6nSzcvnxCobvXdJVrgO9Fy/6COXOG56a2uyzzmU2QDsmtyP46UM+YoaEm9JyxCavhnQbAss=

